// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

#include <iostream>

using namespace std;
char findTheDifference(string s, string t)
{
    int freqS[26] = {0};
    int freqT[26] = {0};

    int n = s.size();
    int n1 = t.size();
    for (int i = 0; i < n; i++)
    {
        freqS[s[i] - 'a']++;
        freqT[t[i] - 'a']++;
    }
    freqT[t[n1 - 1] - 'a']++;

    for (int i = 0; i < 26; i++)
    {
        if (freqT[i] != freqS[i])
        {
            return 'a' + i;
        }
    }
    return ' ';
}

int main()
{
    string s = "";
    string t = "y";

    cout<<"Difference is : "<<findTheDifference(s,t)<<endl;
    return 0;
}